### ISSUE TITLE
Oatmeal does not chat around the current buffer

### ISSUE THREAD

**Issue by fredrikaverpil** [dustinblackman/oatmeal.nvim#11]
Hi 👋  and thanks for a fantastic project! 😄 

When I open a file and then run `:Oatmeal` from within Neovim 0.9.5, I can see the chat starts like this:

```
╭codellama:latest────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Hey there! Let's talk about the following:                                                                     │     ▲
│                                                                                                                │     █
│ File:                                                                                                          │     █
│ /Users/fredrik/code/work/some-repo/some_file.go
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯     █
```

But then if I e.g. ask it to explain each function in the file, it starts talking about a users API and hallucinates badly. It talks about things which are not even part of the project files.

Is it possible that the prompt is not properly populated (with the buffer's contents) when invoking `:Oatmeal`?

**Comment by dustinblackman** [comment]
Hey there! Thanks for the report, you're absolutely right. Lemme get that fixed up.

**Comment by dustinblackman** [comment]
Fixed in https://github.com/dustinblackman/oatmeal.nvim/commit/881d3493d3b72e76f38c3a18262e48c63be16309 and https://github.com/dustinblackman/oatmeal/commit/3655871838d54b15e4f2888dd46712b15d8993be

Thanks!
