### ISSUE TITLE
Context doesn't load when starting Oatmeal with highlighted section

### ISSUE THREAD

**Issue by julwrites** [dustinblackman/oatmeal.nvim#3]
Neovim Version: v0.9.0
OS: MacOS Sonoma Version 14.1 Beta

https://github.com/dustinblackman/oatmeal.nvim/assets/18639913/c3ee1eb3-2237-4dba-9521-2c3b72ed1fa3

Issue: 
On Neovim, Oatmeal launches fine and is interactable as expected, but context is not loaded from the selected text.

**Comment by dustinblackman** [comment]
I'm running Neovim `v0.9.2` on Sonoma, and using an empty Neovim config with only the Oatmeal plugin installed, I can't repro this. It works as expected. 

To confirm, the terminal opening on the left is a Neovim terminal and not a Tmux split, correct?

**Comment by julwrites** [comment]
Ahah, after I upgraded to `v0.9.2` it now works. 

I'm not sure what was in `v0.9.0`, but when I switched back to it, the problem occurs again.

**Comment by dustinblackman** [comment]
Odd, but noted! I've updated the readme. Thanks!
