### ISSUE TITLE
wrong select range

### ISSUE THREAD

**Issue by kapral18** [dustinblackman/oatmeal.nvim#7]
Hi I am having problem with visual selection. Seems like it randomly either rejects the selection completely or takes wrong start and end ranges to send to oatmeal. Anyways I fixed it for myself and suggested it as a PR https://github.com/dustinblackman/oatmeal.nvim/pull/6

Let me know if this is ok otherwise feel free to close it.

**Comment by dustinblackman** [comment]
Interesting! Do you have some code examples or current Neovim configs you could post up? I've been using it quite a bit and haven't run in to any problems.

**Comment by kapral18** [comment]
@dustinblackman  this is my config https://github.com/kapral18/config.nvim but I don't have the commit with the default oatmeal.nvim setup because it didn't work for me I just cloned your repo and fixed the selection for myself and then suggested the fix here. Basically I tried your default suggested setup in docs, and I was getting messed up selection or no selection reflected in oatmeal prompt

**Comment by dustinblackman** [comment]
Understood! Thanks for putting up the PR to fix it. I appreciate it.
