### ISSUE TITLE
Escape out of a Oatmeal.vim session to jump to other windows

### ISSUE THREAD

**Issue by Yeshwanthyk** [dustinblackman/oatmeal.nvim#8]
Thanks for making something I use everyday!

I was wondering if there is already a way, or there could be way to hit escape and move between oatmeal and vim panes.

Right now the only way to work with oatmeal.vim is to exit it and restart a new session. Should I be doing something different?

**Comment by dustinblackman** [comment]
Hey there!

Oatmeal is opening a normal terminal buffer, no magic. You should be able to hit escape to exit terminal mode and enter normal mode without any additional configuration.

Do you have any issues with terminal buffers?

**Comment by Yeshwanthyk** [comment]
Odd. Looks like I had to hit escape twice to get Oatmeal to normal mode. Whereas in the other buffers, escape is working as expected.

I am using Alacritty and Zellij. I tried it on Alacritty without Zellij. On iTerm. On iTerm with Tmux. I needed to hit escape twice.

It works, so I am happy using it this way. But, it certainly is odd.

Thanks for getting back on this!

**Comment by dustinblackman** [comment]
Interesting! Does that happen for whenever you use terminal buffers?

I have this in my config to control how Escape works in a terminal buffer. Whether it's correct or not is up for debate, but it works!

```

vim.api.nvim_set_keymap("t", "<Esc>", "<C-\\><C-n>", { noremap = true })
```

**Comment by Yeshwanthyk** [comment]
Oh, so that did the trick. Cheers!
