### ISSUE TITLE
I getting an error try to run the Oatmeal command

### ISSUE THREAD

**Issue by jim-at-jibba** [dustinblackman/oatmeal.nvim#9]
Hey, 

Thanks for the plugin its just what I am looking for. I love the TUI.

Im running this version of Neovim
<img width="894" alt="Screenshot 2024-01-28 at 06 33 24" src="https://github.com/dustinblackman/oatmeal.nvim/assets/7897877/a2118b70-ac85-4a9e-8e42-0d046b04fc98">
I am struggling to run it in Neovim though. I just get the following error when I run the command.

```
  '<,'>Oatmeal Error executing Lua callback: ...vim-minimal/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Vim:Error executing Lua callback: ...cal/share/nvim-minimal/lazy/oatmeal.nvim/lua/oatmeal.lua:15: attempt to call field 'in_visual_mode' (a nil value)
stack traceback:
	...cal/share/nvim-minimal/lazy/oatmeal.nvim/lua/oatmeal.lua:15: in function 'set_context'
	...cal/share/nvim-minimal/lazy/oatmeal.nvim/lua/oatmeal.lua:87: in function <...cal/share/nvim-minimal/lazy/oatmeal.nvim/lua/oatmeal.lua:86>
	[C]: in function 'cmd'
	...vim-minimal/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <...vim-minimal/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
stack traceback:
	[C]: in function 'cmd'
	...vim-minimal/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <...vim-minimal/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
```
<img width="1668" alt="Screenshot 2024-01-28 at 06 32 20" src="https://github.com/dustinblackman/oatmeal.nvim/assets/7897877/e1e9e0a4-9add-4221-9211-99ae5cfd85ca">

Let me know if there is anything you need.
Thanks

**Comment by dustinblackman** [comment]
Hey there! Thanks for reporting!

That one looks weird, seems to be related to highlighting. Could you walk me through what you had been trying to do? Did you selects a few lines, hit `:`, and entered `Oatmeal`? Or did you use the hotkey?

**Comment by jim-at-jibba** [comment]
Hey, 

Thanks for the speedy reply.

This happens when I make a selection and when I dont. Just trying to run the `Oatmeal` command with `:`. I will try with my minimal setup and see if its a problem my end

**Comment by jim-at-jibba** [comment]
Looks like it is an issue with my config. I will start to remove the likely culprits. Will report back when I know what it just in case others have the same issue

Sorry for wasting your time

**Comment by jim-at-jibba** [comment]
Its so strange, just cant get it to work. Works fine in bare bones init.lua but even when I take everything out of my config I get this error. 

Will close its its not your issue. Thanks

**Comment by dustinblackman** [comment]
Lemme know if you come across the issue! I'd be down to add it to the docs incase other users run in to it.

**Comment by Loungagna** [comment]
I have the same issue.
`NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info`

when calling <cmd>Oatmeal<CR>, the notification shows:
`Error executing Lua callback: ...cois/.local/share/nvim/lazy/oatmeal.nvim/lua/oatmeal.lua:15: attempt to call field 'in_visual_mode' (a nil value)
  stack traceback:                                                                                                                                  
      ...cois/.local/share/nvim/lazy/oatmeal.nvim/lua/oatmeal.lua:15: in function 'set_context'                                                       
      ...cois/.local/share/nvim/lazy/oatmeal.nvim/lua/oatmeal.lua:87: in function <...cois/.local/share/nvim/lazy/oatmeal.nvim/lua/oatmeal.lua:86>`

**Comment by mdietrich16** [comment]
Is this because a user configuration shadows `utils.lua`? The error states that `in_visual_mode` can't be found, which is a member of `utils.lua`, which I also have in my personal config. Maybe that is earlier on the Lua path, so the plugins `utils.lua` does not get loaded and used here?

**Comment by mdietrich16** [comment]
Yup, seems like it. I just put all `oatmeal.nvim` files into another namespace (moved everything under `lua/` to `lua/oatmeal/` and changed the paths in the source files and voila, it works.

**Comment by dustinblackman** [comment]
Ah, so I've built the folder structure incorrectly?

**Comment by mdietrich16** [comment]
Well, not incorrectly per se, but it would probably be wise to properly namespace the modules. I'm not sure how plugins usually do this, what I did was just what first came to mind.

**Comment by Loungagna** [comment]
So what should I do?
Move any folder around? 
change my config files?
Wait for the PR?

**Comment by mdietrich16** [comment]
Well, I can do a PR, but this doesn't require any new code and is essentially a matter of taste, how and where to put the files. You could fix it yourself by renaming your own (presumambly named) `utils.lua` to something else (or move it into a namespace `user.utils` for example) and changing references to that in your code. But I think it should be fixed in this plugin, since others might have the same problem then. So, I'll wait for a commit (or do a PR later).

**Comment by dustinblackman** [comment]
Makes sense! I'll happily accept a PR :) I appreciate it!
